# Setup
title:               Jaybe Park
tagline:             'Data Engineer, Data Scientist, Developer'
description:         '박종범<br>Jaybe Park'
url:                 ''
baseurl:             ''
paginate:            5
paginate_path:       '/contents/page:num'
permalink:           pretty

# About/contact
# author:
#   name:              Mark Otto
#   url:               https://twitter.com/mdo
#   email:             markdotto@gmail.com
author:
  name:              Jaybe Park
  url:               https://github.com/jaybe-park
  email:             jaybe.jongbeom.park@gmail.com

nav:
  Home:           
    - '/'
  Contents:           
    - '/contents/'
    - { Categories: '/contents/categories/' }
    - { Tags: '/contents/tags/' }
  About:          
    - '/about/'

# Where are tags and categories displayed
tag_page: '/contents/tags/'
category_page: '/contents/categories/'

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             0.0.1
google_analytics_id: ''
