# Setup
title:               Jaybe Park
tagline:             'Developer, Data Scientist, Cat Servant'
description:         '박종범<br>Jaybe Park'
url:                 ''
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
# author:
#   name:              Mark Otto
#   url:               https://twitter.com/mdo
#   email:             markdotto@gmail.com
author:
  name:              Jaybe Park
  url:               https://github.com/jaybe-park
  email:             jaybe.jongbeom.park@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             0.0.1
google_analytics_id: ''
